apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "datapower-status"
  namespace: "team-atom"
  labels:
    "team": "team-atom"
spec:
  image: {{image}}
  liveness:
    path: "/api/isAlive"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/isReady"
    port: 3000
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  port: 3000
  envFrom:
    - secret: datapower-status-secret
  env:
    - name: BUCKET_NAME
      value: {{bucketname}}
  
  gcp:
    buckets:
      - name: {{bucketname}}
