name: Build-Deploy-Preprod
on:
  push:
    branches:
      - "dev"
    paths-ignore:
      - README.md
      - CODEOWNERS
  workflow_dispatch:

jobs:
  "build":
    name: "build app and push"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-atom #
          docker_context: . # optional, default .
          push_image: true # optional, default true
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret

      - name: Deploy dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ".nais/nais.yaml"
          VARS: .nais/dev.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}

#  "deployAlertsToDev":
#    name: "Deploy alerts to dev"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#      - uses: "actions/checkout@v3"
#      - name: "Deploy alerts to DEV"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "dev-gcp"
#          "RESOURCE": ".nais/alerts-dev.yaml"
#          "VARS": ".nais/dev.yaml"
#  "deployAlertsToProd":
#    name: "Deploy alerts to prod"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#      - uses: "actions/checkout@v3"
#      - name: "Deploy alerts to PROD"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "prod-gcp"
#          "RESOURCE": ".nais/alerts-prod.yaml"
#          "VARS": ".nais/prod.yaml"
