name: Build-Deploy-Preprod
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  IMAGE: "ghcr.io/navikt/datapower-status:${{ github.sha }}"

jobs:
  "build":
    name: "build app and push"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with:
          node-version: 14
      - name: "install dependencies an build react"
        run: "yarn install --frozen-lockfile && yarn build"
      - name: "setup server"
        run: "yarn install --frozen-lockfile --prod"
      - name: build docker image
        run: |
          docker build --pull --tag ${{ env.IMAGE }}  .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}

  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@master"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/nais.yaml"
          VARS: ".nais/dev.yaml"
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}

#  "deployAlertsToDev":
#    name: "Deploy alerts to dev"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#      - uses: "actions/checkout@v2"
#      - name: "Deploy alerts to DEV"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "dev-gcp"
#          "RESOURCE": ".nais/alerts-dev.yaml"
#          "VARS": ".nais/dev.yaml"
#  "deployAlertsToProd":
#    name: "Deploy alerts to prod"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#      - uses: "actions/checkout@v2"
#      - name: "Deploy alerts to PROD"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "prod-gcp"
#          "RESOURCE": ".nais/alerts-prod.yaml"
#          "VARS": ".nais/prod.yaml"
