name: Build-Deploy-Prod
on:
  push:
    branches:
      - "main"

env:
  IMAGE: ghcr.io/navikt/datapower-status:${{ github.sha }}

jobs:
  "build":
    name: "build app and push"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3.7.0"
        with:
          node-version: 18
      - name: "install dependencies and build application"
        run: "yarn install --frozen-lockfile && yarn build"
      - name: build docker image
        run: |
          docker build --pull --tag ${{ env.IMAGE }}  .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}

  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@master"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/nais.yaml"
          VARS: ".nais/dev.yaml"
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}

  "deployAppToProd":
    name: "Deploy app to prod"
    needs: "deployAppToDev"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@master"
        env:
          APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          CLUSTER: "prod-gcp"
          RESOURCE: ".nais/nais.yaml"
          VARS: ".nais/prod.yaml"
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}
#  "deployAlertsToDev":
#    name: "Deploy alerts to dev"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#      - uses: "actions/checkout@v3"
#      - name: "Deploy alerts to DEV"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "dev-gcp"
#          "RESOURCE": ".nais/alerts-dev.yaml"
#          "VARS": ".nais/dev.yaml"
#  "deployAlertsToProd":
#    name: "Deploy alerts to prod"
#    needs: "build"
#    runs-on: "ubuntu-18.04"
#    steps:
#      - uses: "actions/checkout@v3"
#      - name: "Deploy alerts to PROD"
#        uses: "nais/deploy/actions/deploy@v1"
#        env:
#          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#          "CLUSTER": "prod-gcp"
#          "RESOURCE": ".nais/alerts-prod.yaml"
#          "VARS": ".nais/prod.yaml"
